project:
  type: book
  output-dir: docs

book:
  title: "Portfolio Computationele Biologie"
  author: "Jouw naam"
  date: today
  description: "September 2026 – Februari 2027"
  chapters:
    - index.qmd
    - ANT_stochastische_var.qmd
    - antwoorden/ANT_log_theorie.qmd
    - Regressie_theorie.qmd
    - Differentiaalvergelijkingen_theorie.qmd
    - sepia_standaardfout_theorie.qmd
    - genetic_drift.qmd
    - meta-populaties.qmd
    - references.qmd
  appendices:
    - ANT_mais_pract.qmd
    - antwoorden/ANT_log_pract.qmd
    - Bradford_statistiek.qmd
    - Sepia_Mantel.qmd  

bibliography: references.bib

link-citations: true

number-sections: true
    
format:
  html:
    css: styles.css

crossref:
  chapters: true
  exr-prefix: "Vraag"
  eq-prefix: "Vergelijking"
  fig-prefix: "Figuur"
  sec-prefix: "Hoofdstuk"

editor: visual
language:
  ui:
    chapter_name: ""
  crossref-exr-title: "Vraag"
  crossref-ch-title: "Hoofdstuk"
  crossref-sec-prefix: "Hoofdstuk"

